## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Create highly available Tomcat setup with web application accessing MDS in Oracle Cloud Infrastructure"
stackDescription: "Deploy highly available Tomcat setup with web application accessing MySQL Database Service (MDS) in Oracle Cloud Infrastructure."
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid

- title: Required Configuration
  visible: true  
  variables:
  - mysql_db_system_admin_password
  - compartment_ocid
  - region
  - availablity_domain_name 

- title: Optional Configuration
  visible: true
  variables:
  - lb_shape  
  - igw_display_name
  - vcn01_cidr_block
  - vcn01_dns_label
  - vcn01_display_name
  - vcn01_subnet_pub01_cidr_block
  - vcn01_subnet_pub01_display_name
  - vcn01_subnet_pub02_cidr_block
  - vcn01_subnet_pub02_display_name  
  - vcn01_subnet_app01_cidr_block
  - vcn01_subnet_app01_display_name 
  - vcn01_subnet_db01_cidr_block
  - vcn01_subnet_db01_display_name
  - InstanceShape
  - OsImage
  - mysql_db_system_admin_username
  - mysql_db_name
  - mysql_db_system_backup_policy_is_enabled
  - mysql_db_system_data_storage_size_in_gb
  - mysql_db_system_display_name
  - mysql_db_system_hostname_label

variables:
  
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: Compartment
    description: "Compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: Region
    description: "Region where you want to deploy the resources defined by this stack."

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Availability Domain to be chosen"
    dependsOn:
      compartmentId: ${compartment_ocid}

  mysql_db_system_admin_password:
    type: password
    required: true
    visibile: true
    title: "MDS Admin Password"
    description: "Type MySQL DBSystem (MDS) Admin Password"
    minLength: 9
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 
 
  # Optional Configuration  
  
  lb_shape:
    type: enum
    title: "LoadBalanacer Shape"
    description: "Choose LoadBalanacer Shape"
    default: "100Mbps"
    required: false 
    enum:
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  igw_display_name:
    type: string
    required: false
    title: "InternetGateway Display Name"
    description: "Type InternetGateway Display Name."
    default: "internet-gateway"

  vcn01_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR Block"
    description: "Choose CIDR block for your VCN."
    default: "10.0.0.0/16"

  vcn01_dns_label:
    type: string
    required: false
    title: "VCN DNS Label"
    description: "Choose DNS Label for your VCN."
    default: "vcn01"

  vcn01_display_name:
    type: string
    required: false
    title: "VCN Display Name"
    description: "Choose Display Name for your VCN."
    default: "vcn01"

  vcn01_subnet_pub01_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Load Balancer Public Subnet CIDR Block"
    description: "Choose CIDR block for your Load Balancer Public Subnet."
    default: "10.0.1.0/24"

  vcn01_subnet_pub01_display_name:
    type: string
    required: false
    title: "Load Balancer Public Subnet Display Name"
    description: "Choose Display Name for your Load Balancer Public Subnet."
    default: "vcn01_subnet_pub01"

  vcn01_subnet_pub02_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Bastion Host Public Subnet CIDR Block"
    description: "Choose CIDR block for your Bastion Host Public Subnet."
    default: "10.0.2.0/24"

  vcn01_subnet_pub02_display_name:
    type: string
    required: false
    title: "Bastion Host Public Subnet Display Name"
    description: "Choose Display Name for your Bastion Host Public Subnet."
    default: "vcn01_subnet_pub02"

  vcn01_subnet_app01_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Tomcat Servers Public Subnet CIDR Block"
    description: "Choose CIDR block for your Tomcat Servers Public Subnet."
    default: "10.0.10.0/24"

  vcn01_subnet_app01_display_name:
    type: string
    required: false
    title: "Tomcat Servers Public Subnet Display Name"
    description: "Choose Display Name for your Tomcat Servers Public Subnet."
    default: "vcn01_subnet_app01"

  vcn01_subnet_db01_cidr_block:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "MDS Private Subnet CIDR Block"
    description: "Choose CIDR block for your MDS Private Subnet."
    default: "10.0.20.0/24"

  vcn01_subnet_db01_display_name:
    type: string
    required: false
    title: "MDS Private Subnet Display Name"
    description: "Choose Display Name for your MDS Private Subnet."
    default: "vcn01_subnet_db01"

  InstanceShape:
    type: oci:core:instanceshape:name
    required: false
    title: "Instance Shape"
    description: "A shape is a template that determines the number of CPUs, amount of memory, and other resources allocated to a newly created instance."
    default: "VM.Standard2.1"
    dependsOn:
      compartmentId: ${compartment_ocid}
  
  OsImage:
    type: string
    required: false
    title: "OS Image"
    description: "Choose OS Image determines the operating system for the instance."
    default: "Oracle-Linux-7.8-2020.05.26-0"

  mysql_db_system_admin_username:
    type: string
    required: false
    title: "MDS Admin Username"
    description: "Type MDS Admin Username."
    default: "admin"

  mysql_db_name:
    type: string
    required: false
    title: "MDS DB Name"
    description: "Type MDS DB Name."
    default: "mydb"

  mysql_db_system_backup_policy_is_enabled:
    type: boolean 
    default: true
    required: false
    title: "MDS DBSystem Backup Policy Enabled"
    description: "MDS DBSystem Backup Policy Enabled."

  mysql_db_system_data_storage_size_in_gb:
    type: number
    required: false
    minimum: 50
    maximum: 65536
    multipleOf: 1
    default: 50 
    title: "MDS DBSystem Data Storage size in GB"
    description: "Choose MDS DBSystem Data Storage size in GB."

  mysql_db_system_display_name: 
    type: string
    required: false
    title: "MDS DBSystem Display Name"
    description: "Type MDS DBSystem Display Name."
    default: "mysql_service"

  mysql_db_system_hostname_label: 
    type: string
    required: false
    title: "MDS DBSystem Hostname Label"
    description: "Type MDS DBSystem Hostname Label."
    default: "mysqlhost"

outputs:

  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: copyableString
    visible: true

  loadbalancer_public_url:
    title: "Loadbalancer Public URL"
    displayText: "Loadbalancer Public URL"
    type: copyableString
    visible: true

  bastion_public_ip:
    title: "Bastion Host Public IP"
    displayText: "Bastion Host Public IP"
    type: string
    visible: true

  tomcat-server1_private_ip:
    title: "Tomcat Server1 Private IP"
    displayText: "Tomcat Server1 Private IP"
    type: string
    visible: true

  tomcat-server2_private_ip:
    title: "Tomcat Server2 Private IP"
    displayText: "Tomcat Server2 Private IP"
    type: string
    visible: true
