name: Build and push Docker images

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-war:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Build ToDo WebApp
        run: |
          docker  run --rm --name todo-build \
          -v "$(pwd)/java":/usr/src:z \
          -w /usr/src \
          maven:3.3-jdk-8 mvn --batch-mode clean verify install